import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private regiones = [
    {"id":3,"nombre":"Antofagasta"},
    {"id":1,"nombre":"Arica y Parinacota"},
    {"id":4,"nombre":"Atacama"},
    {"id":5,"nombre":"Coquimbo"},
    {"id":8,"nombre":"Libertador General Bernardo O'Higgins"},
    {"id":9,"nombre":"Maule"},
    {"id":7,"nombre":"Metropolitana de Santiago"},
    {"id":15,"nombre":"Región de Aysén del General Carlos Ibáñez del Campo"},
    {"id":12,"nombre":"Región de La Araucanía"},
    {"id":14,"nombre":"Región de Los Lagos"},
    {"id":13,"nombre":"Región de Los Ríos"},
    {"id":16,"nombre":"Región de Magallanes y de la Antártica Chilena"},
    {"id":10,"nombre":"Región de Ñuble"},
    {"id":11,"nombre":"Región del Biobío"},
    {"id":2,"nombre":"Tarapacá"},
    {"id":6,"nombre":"Valparaíso"}]
    // ... (otros datos de regiones)
  ;

  private comunas = [
    {"id": 8, "nombre": "Antofagasta"},
    {"id": 9, "nombre": "Mejillones"},
    {"id": 10, "nombre": "Sierra Gorda"},
    {"id": 11, "nombre": "Taltal"},
    {"id": 12, "nombre": "Calama"},
    {"id": 13, "nombre": "Ollagüe"},
    {"id": 14, "nombre": "San Pedro de Atacama"},
    {"id": 15, "nombre": "Tocopilla"},
    {"id": 16, "nombre": "María Elena"},
    {"id": 17, "nombre": "Copiapó"},
    {"id": 18, "nombre": "Caldera"},
    {"id": 19, "nombre": "Tierra Amarilla"},
    {"id": 20, "nombre": "Chañaral"},
    {"id": 21, "nombre": "Diego de Almagro"},
    {"id": 22, "nombre": "Vallenar"},
    {"id": 23, "nombre": "Alto del Carmen"},
    {"id": 24, "nombre": "Freirina"},
    {"id": 25, "nombre": "Huasco"},
    {"id": 26, "nombre": "La Serena"},
    {"id": 27, "nombre": "Coquimbo"},
    {"id": 28, "nombre": "Andacollo"},
    {"id": 29, "nombre": "La Higuera"},
    {"id": 30, "nombre": "Paihuano"},
    {"id": 31, "nombre": "Vicuña"},
    {"id": 32, "nombre": "Illapel"},
    {"id": 33, "nombre": "Canela"},
    {"id": 34, "nombre": "Los Vilos"},
    {"id": 35, "nombre": "Salamanca"},
    {"id": 36, "nombre": "Ovalle"},
    {"id": 37, "nombre": "Combarbalá"},
    {"id": 38, "nombre": "Monte Patria"},
    {"id": 39, "nombre": "Punitaqui"},
    {"id": 40, "nombre": "Río Hurtado"},
    {"id": 41, "nombre": "Valparaíso"},
    {"id": 42, "nombre": "Casablanca"},
    {"id": 43, "nombre": "Concón"},
    {"id": 44, "nombre": "Juan Fernández"},
    {"id": 45, "nombre": "Puchuncaví"},
    {"id": 46, "nombre": "Quintero"},
    {"id": 47, "nombre": "Viña del Mar"},
    {"id": 48, "nombre": "Isla de Pascua"},
    {"id": 49, "nombre": "Los Andes"},
    {"id": 50, "nombre": "Calle Larga"},
    {"id": 51, "nombre": "Rinconada"},
    {"id": 52, "nombre": "San Esteban"},
    {"id": 53, "nombre": "La Ligua"},
    {"id": 54, "nombre": "Cabildo"},
    {"id": 55, "nombre": "Papudo"},
    {"id": 56, "nombre": "Petorca"},
    {"id": 57, "nombre": "Zapallar"},
    {"id": 58, "nombre": "Quillota"},
    {"id": 59, "nombre": "La Calera"},
    {"id": 60, "nombre": "Hijuelas"},
    {"id": 61, "nombre": "La Cruz"},
    {"id": 62, "nombre": "Nogales"},
    {"id": 63, "nombre": "San Antonio"},
    {"id": 64, "nombre": "Algarrobo"},
    {"id": 65, "nombre": "Cartagena"},
    {"id": 66, "nombre": "El Quisco"},
    {"id": 67, "nombre": "El Tabo"},
    {"id": 68, "nombre": "Santo Domingo"},
    {"id": 69, "nombre": "San Felipe"},
    {"id": 70, "nombre": "Catemu"},
    {"id": 71, "nombre": "Llay-Llay"},
    {"id": 72, "nombre": "Panquehue"},
    {"id": 73, "nombre": "Putaendo"},
    {"id": 74, "nombre": "Santa María"},
    {"id": 75, "nombre": "Quilpué"},
    {"id": 76, "nombre": "Limache"},
    {"id": 77, "nombre": "Olmué"},
    {"id": 78, "nombre": "Villa Alemana"},
    {"id": 79, "nombre": "Rancagua"},
    {"id": 80, "nombre": "Codegua"},
    {"id": 81, "nombre": "Coinco"},
    {"id": 82, "nombre": "Coltauco"},
    {"id": 83, "nombre": "Doñihue"},
    {"id": 84, "nombre": "Graneros"},
    {"id": 85, "nombre": "Las Cabras"},
    {"id": 86, "nombre": "Machalí"},
    {"id": 87, "nombre": "Malloa"},
    {"id": 88, "nombre": "Mostazal"},
    {"id": 89, "nombre": "Olivar"},
    {"id": 90, "nombre": "Peumo"},
    {"id": 91, "nombre": "Pichidegua"},
    {"id": 92, "nombre": "Quinta de Tilcoco"},
    {"id": 93, "nombre": "Rengo"},
    {"id": 94, "nombre": "Requínoa"},
    {"id": 95, "nombre": "San Vicente"},
    {"id": 96, "nombre": "Pichilemu"},
    {"id": 97, "nombre": "La Estrella"},
    {"id": 98, "nombre": "Litueche"},
    {"id": 99, "nombre": "Marchihue"},
    {"id": 100, "nombre": "Navidad"},
    {"id": 101, "nombre": "Paredones"},
    {"id": 102, "nombre": "San Fernando"},
    {"id": 103, "nombre": "Chépica"},
    {"id": 104, "nombre": "Chimbarongo"},
    {"id": 105, "nombre": "Lolol"},
    {"id": 106, "nombre": "Nancagua"},
    {"id": 107, "nombre": "Palmilla"},
    {"id": 108, "nombre": "Peralillo"},
    {"id": 109, "nombre": "Placilla"},
    {"id": 110, "nombre": "Pumanque"},
    {"id": 111, "nombre": "Santa Cruz"},
    {"id": 112, "nombre": "Talca"},
    {"id": 113, "nombre": "Constitución"},
    {"id": 114, "nombre": "Curepto"},
    {"id": 115, "nombre": "Empedrado"},
    {"id": 116, "nombre": "Maule"},
    {"id": 117, "nombre": "Pelarco"},
    {"id": 118, "nombre": "Pencahue"},
    {"id": 119, "nombre": "Río Claro"},
    {"id": 120, "nombre": "San Clemente"},
    {"id": 121, "nombre": "San Rafael"},
    {"id": 122, "nombre": "Cauquenes"},
    {"id": 123, "nombre": "Chanco"},
    {"id": 124, "nombre": "Pelluhue"},
    {"id": 125, "nombre": "Curicó"},
    {"id": 126, "nombre": "Hualañé"},
    {"id": 127, "nombre": "Licantén"},
    {"id": 128, "nombre": "Molina"},
    {"id": 129, "nombre": "Rauco"},
    {"id": 130, "nombre": "Romeral"},
    {"id": 131, "nombre": "Sagrada Familia"},
    {"id": 132, "nombre": "Teno"},
    {"id": 133, "nombre": "Vichuquén"},
    {"id": 134, "nombre": "Linares"},
    {"id": 135, "nombre": "Colbún"},
    {"id": 136, "nombre": "Longaví"},
    {"id": 137, "nombre": "Parral"},
    {"id": 138, "nombre": "Retiro"},
    {"id": 139, "nombre": "San Javier"},
    {"id": 140, "nombre": "Villa Alegre"},
    {"id": 141, "nombre": "Yerbas Buenas"},
    {"id": 142, "nombre": "Chillán"},
    {"id": 143, "nombre": "Bulnes"},
    {"id": 144, "nombre": "Chillán Viejo"},
    {"id": 145, "nombre": "El Carmen"},
    {"id": 146, "nombre": "Pemuco"},
    {"id": 147, "nombre": "Pinto"},
    {"id": 148, "nombre": "Quillón"},
    {"id": 149, "nombre": "San Ignacio"},
    {"id": 150, "nombre": "Yungay"},
    {"id": 151, "nombre": "Quirihue"},
    {"id": 152, "nombre": "Cobquecura"},
    {"id": 153, "nombre": "Coelemu"},
    {"id": 154, "nombre": "Ninhue"},
    {"id": 155, "nombre": "Portezuelo"},
    {"id": 156, "nombre": "Ránquil"},
    {"id": 157, "nombre": "Treguaco"},
    {"id": 158, "nombre": "San Carlos"},
    {"id": 159, "nombre": "Coihueco"},
    {"id": 160, "nombre": "Ñiquén"},
    {"id": 161, "nombre": "San Fabián"},
    {"id": 162, "nombre": "San Nicolás"},
    {"id": 163, "nombre": "Concepción"},
    {"id": 164, "nombre": "Coronel"},
    {"id": 165, "nombre": "Chiguayante"},
    {"id": 166, "nombre": "Florida"},
    {"id": 167, "nombre": "Hualqui"},
    {"id": 168, "nombre": "Lota"},
    {"id": 169, "nombre": "Penco"},
    {"id": 170, "nombre": "San Pedro de La Paz"},
    {"id": 171, "nombre": "Santa Juana"},
    {"id": 172, "nombre": "Talcahuano"},
    {"id": 173, "nombre": "Tomé"},
    {"id": 174, "nombre": "Hualpén"},
    {"id": 175, "nombre": "Lebu"},
    {"id": 176, "nombre": "Arauco"},
    {"id": 177, "nombre": "Cañete"},
    {"id": 178, "nombre": "Contulmo"},
    {"id": 179, "nombre": "Curanilahue"},
    {"id": 180, "nombre": "Los Álamos"},
    {"id": 181, "nombre": "Tirúa"},
    {"id": 182, "nombre": "Los Ángeles"},
    {"id": 183, "nombre": "Antuco"},
    {"id": 184, "nombre": "Cabrero"},
    {"id": 185, "nombre": "Laja"},
    {"id": 186, "nombre": "Mulchén"},
    {"id": 187, "nombre": "Nacimiento"},
    {"id": 188, "nombre": "Negrete"},
    {"id": 189, "nombre": "Quilaco"},
    {"id": 190, "nombre": "Quilleco"},
    {"id": 191, "nombre": "San Rosendo"},
    {"id": 192, "nombre": "Santa Bárbara"},
    {"id": 193, "nombre": "Tucapel"},
    {"id": 194, "nombre": "Yumbel"},
    {"id": 195, "nombre": "Alto Biobío"},
    {"id": 196, "nombre": "Temuco"},
    {"id": 197, "nombre": "Carahue"},
    {"id": 198, "nombre": "Cunco"},
    {"id": 199, "nombre": "Curarrehue"},
    {"id": 200, "nombre": "Freire"},
    {"id": 201, "nombre": "Galvarino"},
    {"id": 202, "nombre": "Gorbea"},
    {"id": 203, "nombre": "Lautaro"},
    {"id": 204, "nombre": "Loncoche"},
    {"id": 205, "nombre": "Melipeuco"},
    {"id": 206, "nombre": "Nueva Imperial"},
    {"id": 207, "nombre": "Padre Las Casas"},
    {"id": 208, "nombre": "Perquenco"},
    {"id": 209, "nombre": "Pitrufquén"},
    {"id": 210, "nombre": "Pucón"},
    {"id": 211, "nombre": "Saavedra"},
    {"id": 212, "nombre": "Teodoro Schmidt"},
    {"id": 213, "nombre": "Toltén"},
    {"id": 214, "nombre": "Vilcún"},
    {"id": 215, "nombre": "Villarrica"},
    {"id": 216, "nombre": "Cholchol"},
    {"id": 217, "nombre": "Angol"},
    {"id": 218, "nombre": "Collipulli"},
    {"id": 219, "nombre": "Curacautín"},
    {"id": 220, "nombre": "Ercilla"},
    {"id": 221, "nombre": "Lonquimay"},
    {"id": 222, "nombre": "Los Sauces"},
    {"id": 223, "nombre": "Lumaco"},
    {"id": 224, "nombre": "Purén"},
    {"id": 225, "nombre": "Renaico"},
    {"id": 226, "nombre": "Traiguén"},
    {"id": 227, "nombre": "Victoria"},
    {"id": 228, "nombre": "Valdivia"},
    {"id": 229, "nombre": "Corral"},
    {"id": 230, "nombre": "Lanco"},
    {"id": 231, "nombre": "Los Lagos"},
    {"id": 232, "nombre": "Máfil"},
    {"id": 233, "nombre": "Mariquina"},
    {"id": 234, "nombre": "Paillaco"},
    {"id": 235, "nombre": "Panguipulli"},
    {"id": 236, "nombre": "La Unión"},
    {"id": 237, "nombre": "Futrono"},
    {"id": 238, "nombre": "Lago Ranco"},
    {"id": 239, "nombre": "Río Bueno"},
    {"id": 240, "nombre": "Puerto Montt"},
    {"id": 241, "nombre": "Calbuco"},
    {"id": 242, "nombre": "Cochamó"},
    {"id": 243, "nombre": "Fresia"},
    {"id": 244, "nombre": "Frutillar"},
    {"id": 245, "nombre": "Los Muermos"},
    {"id": 246, "nombre": "Llanquihue"},
    {"id": 247, "nombre": "Maullín"},
    {"id": 248, "nombre": "Puerto Varas"},
    {"id": 249, "nombre": "Castro"},
    {"id": 250, "nombre": "Ancud"},
    {"id": 251, "nombre": "Chonchi"},
    {"id": 252, "nombre": "Curaco de Vélez"},
    {"id": 253, "nombre": "Dalcahue"},
    {"id": 254, "nombre": "Puqueldón"},
    {"id": 255, "nombre": "Queilén"},
    {"id": 256, "nombre": "Quellón"},
    {"id": 257, "nombre": "Quemchi"},
    {"id": 258, "nombre": "Quinchao"},
    {"id": 259, "nombre": "Osorno"},
    {"id": 260, "nombre": "Puerto Octay"},
    {"id": 261, "nombre": "Purranque"},
    {"id": 262, "nombre": "Puyehue"},
    {"id": 263, "nombre": "Río Negro"},
    {"id": 264, "nombre": "San Juan de la Costa"},
    {"id": 265, "nombre": "San Pablo"},
    {"id": 266, "nombre": "Chaitén"},
    {"id": 267, "nombre": "Futaleufú"},
    {"id": 268, "nombre": "Hualaihué"},
    {"id": 269, "nombre": "Palena"},
    {"id": 270, "nombre": "Coyhaique"},
    {"id": 271, "nombre": "Lago Verde"},
    {"id": 272, "nombre": "Aysén"},
    {"id": 273, "nombre": "Cisnes"},
    {"id": 274, "nombre": "Guaitecas"},
    {"id": 275, "nombre": "Cochrane"},
    {"id": 276, "nombre": "O'Higgins"},
    {"id": 277, "nombre": "Tortel"},
    {"id": 278, "nombre": "Chile Chico"},
    {"id": 279, "nombre": "Río Ibáñez"},
    {"id": 280, "nombre": "Punta Arenas"},
    {"id": 281, "nombre": "Laguna Blanca"},
    {"id": 282, "nombre": "Río Verde"},
    {"id": 283, "nombre": "San Gregorio"},
    {"id": 284, "nombre": "Cabo de Hornos"},
    {"id": 285, "nombre": "Antártica"},
    {"id": 286, "nombre": "Porvenir"},
    {"id": 287, "nombre": "Primavera"},
    {"id": 288, "nombre": "Timaukel"},
    {"id": 289, "nombre": "Natales"},
    {"id": 290, "nombre": "Torres del Paine"},
    {"id":291,"nombre":"Santiago"},
    {"id":292,"nombre":"Cerrillos"},
    {"id":293,"nombre":"Cerro Navia"},
    {"id":294,"nombre":"Conchalí"},
    {"id":295,"nombre":"El Bosque"},
    {"id":296,"nombre":"Estación Central"},
    {"id":297,"nombre":"Huechuraba"},
    {"id":298,"nombre":"Independencia"},
    {"id":299,"nombre":"La Cisterna"},
    {"id":300,"nombre":"La Florida"},
    {"id":301,"nombre":"La Granja"},
    {"id":302,"nombre":"La Pintana"},
    {"id":303,"nombre":"La Reina"},
    {"id":304,"nombre":"Las Condes"},
    {"id":305,"nombre":"Lo Barnechea"},
    {"id":306,"nombre":"Lo Espejo"},
    {"id":307,"nombre":"Lo Prado"},
    {"id":308,"nombre":"Macul"},
    {"id":309,"nombre":"Maipú"},
    {"id":310,"nombre":"Ñuñoa"},
    {"id":311,"nombre":"Pedro Aguirre Cerda"},
    {"id":312,"nombre":"Peñalolén"},
    {"id":313,"nombre":"Providencia"},
    {"id":314,"nombre":"Pudahuel"},
    {"id":315,"nombre":"Quilicura"},
    {"id":316,"nombre":"Quinta Normal"},
    {"id":317,"nombre":"Recoleta"},
    {"id":318,"nombre":"Renca"},
    {"id":319,"nombre":"San Joaquín"},
    {"id":320,"nombre":"San Miguel"},
    {"id":321,"nombre":"San Ramón"},
    {"id":322,"nombre":"Vitacura"},
    {"id":323,"nombre":"Puente Alto"},
    {"id":324,"nombre":"Pirque"},
    {"id":325,"nombre":"San José de Maipo"},
    {"id":326,"nombre":"Colina"},
    {"id":327,"nombre":"Lampa"},
    {"id":328,"nombre":"Til Til"},
    {"id":329,"nombre":"San Bernardo"},
    {"id":330,"nombre":"Buin"},
    {"id":331,"nombre":"Calera de Tango"},
    {"id":332,"nombre":"Paine"},
    {"id":333,"nombre":"Melipilla"},
    {"id":334,"nombre":"Alhué"},
    {"id":335,"nombre":"Curacaví"},
    {"id":336,"nombre":"María Pinto"},
    {"id":337,"nombre":"San Pedro"},
    {"id":338,"nombre":"Talagante"},
    {"id":339,"nombre":"El Monte"},
    {"id":340,"nombre":"Isla de Maipo"},
    {"id":341,"nombre":"Padre Hurtado"},
    {"id":342,"nombre":"Peñaflor"},
    {"id": 343, "nombre": "Arica"},
    {"id": 344, "nombre": "Camarones"},
    {"id": 345, "nombre": "Putre"},
    {"id": 346, "nombre": "General Lagos"}

    // ... (otros datos de comunas)
  ];

  constructor() { }

  getRegionNombrePorId(regionId: number): string {
    const region = this.regiones.find(region => region.id === regionId);
    return region ? region.nombre : '';
  }

  getComunaNombrePorId(comunaId: number): string {
    const comuna = this.comunas.find(comuna => comuna.id === comunaId);
    return comuna ? comuna.nombre : '';
  }
}




